{% set version = "0.0.1" %}

package:
  name: fununifrac
  version: {{ version }}

source:
  url: https://github.com/KoslickiLab/FunUniFrac/archive/v{{ version }}.tar.gz
  sha256: 75a73441fa44d57f8c0061f6d6e60dea20d9a963e96c5af346b1f4cd3bd029a5

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6, < 3.10
    - pip
    - setuptools >=24.2.0

  run:
    - python
    - blist
    - scipy==1.8.0
    - networkx==2.8.4
    - numpy==1.23.2
    - pandas==1.4.3
    - pyemd==0.5.1
    - matplotlib
    - pytest
    - sparse
    - requests
    - seaborn

test:
  imports:
    - fununifrac

  commands:
    - compute_fununifrac.py -h
    - compute_edge_lengths.py -h
    - make_edges.py -h

about:
  home: https://github.com/KoslickiLab/FunUniFrac
  summary: 'A repository to implement UniFrac, but on functional profiles of metagenomic data.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/KoslickiLab/FunUniFrac
  doc_url: https://github.com/KoslickiLab/FunUniFrac

extra:
  identifiers:
    - TBD
  recipe-maintainers:
    - akp6031
    - raquellewei
  authors:
    - dkoslicki
    - akp6031
    - raquellewei
    - chunyuma
    - mahmudhera
    - ShaopengLiu1
  
